# Generated by Django 5.0.3 on 2024-06-10 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_rename_slug_performer_short_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='region',
            name='uniq_region',
        ),
        migrations.AddField(
            model_name='modelrun',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='region',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(
                condition=models.Q(('owner__isnull', True)),
                fields=('name',),
                name='unique_region_with_null_owner',
                violation_error_message='Region already exists with a null owner.',
            ),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(
                condition=models.Q(('owner__isnull', False)),
                fields=('name', 'owner'),
                name='unique_region_with_owner',
                violation_error_message='Region already exists with \
                    this name and owner.',
            ),
        ),
    ]
